@base = http://localhost/Programacion3/trabajoPractico-Final
@token_socio = YOUR_TOKEN_HERE
@token_mozo = YOUR_TOKEN_HERE
@from = 2026-01-01
@to = 2026-12-31

### ==============================
### EMPLEADOS - LISTAR
### ==============================
GET {{base}}/empleados
Authorization: Bearer {{token_socio}}

### ==============================
### EMPLEADOS - ALTA
### ==============================
POST {{base}}/empleados
Authorization: Bearer {{token_socio}}
Content-Type: application/json

{
  "nombre": "Empleado Prueba",
  "email": "empleado.prueba@gmail.com",
  "clave": "1234",
  "tipo": "mozo"
}
