@base_url = http://localhost/Programacion3/trabajoPractico-Final
@token_socio = YOUR_TOKEN_HERE
@token_mozo = YOUR_TOKEN_HERE
@token_cocinero = YOUR_TOKEN_HERE

### ==============================
### MESAS - LISTAR (PUBLICO)
### ==============================
GET {{base_url}}/mesas

### ==============================
### MESAS - LISTAR POR ESTADO (PUBLICO)
### ==============================
GET {{base_url}}/mesas/por-estado

### ==============================
### MESAS - ALTA CON SOCIO
### ==============================
POST {{base_url}}/mesas
Authorization: Bearer {{token_socio}}   
Content-Type: application/json

{
  "id": "A0001"
}

### ==============================
### MESAS - ALTA CON MOZO
### ==============================
POST {{base_url}}/mesas
Authorization: Bearer {{token_mozo}}
Content-Type: application/json

{
  "id": "A0002"
}
