@base_url = http://localhost/Programacion3/trabajoPractico-Final
@token_socio = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzU2MTA5NTksImV4cCI6MTc3NTYxNDU1OSwiZGF0YSI6eyJpZCI6NSwibm9tYnJlIjoiU29jaW8xIiwiZW1haWwiOiJzb2NpbzFAZ21haWwuY29tIiwicm9sIjoic29jaW8ifX0.u68XshNL0CVdd22lwleUS8U2ItcFS8VOdwpDp7zkhG8
@token_mozo = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzU2MTA5OTMsImV4cCI6MTc3NTYxNDU5MywiZGF0YSI6eyJpZCI6NCwibm9tYnJlIjoiTW96bzEiLCJlbWFpbCI6Im1vem8xQGdtYWlsLmNvbSIsInJvbCI6Im1vem8ifX0.ZWXRo9HTJsVkjbWZMKbC0cXWZw4QZQ0iqkg8j6Wqjfw
@token_cocinero = PEGAR_TOKEN_COCINERO

### ==============================
### MESAS - LISTAR (PUBLICO)
### ==============================
GET {{base_url}}/mesas

### ==============================
### MESAS - LISTAR POR ESTADO (PUBLICO)
### ==============================
GET {{base_url}}/mesas/por-estado

### ==============================
### MESAS - ALTA CON SOCIO
### ==============================
POST {{base_url}}/mesas
Authorization: Bearer {{token_socio}}   
Content-Type: application/json

{
  "id": "A0001"
}

### ==============================
### MESAS - ALTA CON MOZO
### ==============================
POST {{base_url}}/mesas
Authorization: Bearer {{token_mozo}}
Content-Type: application/json

{
  "id": "A0002"
}
