@base_url = http://localhost/Programacion3/trabajoPractico-Final

@token_socio = YOUR_TOKEN_HERE

@from = 2026-01-01 00:00:00

@to = 2026-12-31 23:59:59

### ==============================
### MÁS VENDIDOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/mas-vendidos?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### MENOS VENDIDOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/menos-vendidos?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### FUERA DE TIEMPO
### ==============================
GET {{base_url}}/pedidos/estadisticas/fuera-de-tiempo?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### CANCELADOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/cancelados?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### CERRADOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/cerrados?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}