@base_url = http://localhost/Programacion3/trabajoPractico-Final

@token_socio = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzYxMTIwNDEsImV4cCI6MTc3NjExNTY0MSwiZGF0YSI6eyJpZCI6NSwibm9tYnJlIjoiU29jaW8xIiwiZW1haWwiOiJzb2NpbzFAZ21haWwuY29tIiwicm9sIjoic29jaW8ifX0.nObzASfpPHix-XBsahs8xjEycXf-tctScN5gSYbGEy4

@from = 2026-01-01 00:00:00

@to = 2026-12-31 23:59:59

### ==============================
### MÁS VENDIDOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/mas-vendidos?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### MENOS VENDIDOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/menos-vendidos?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### FUERA DE TIEMPO
### ==============================
GET {{base_url}}/pedidos/estadisticas/fuera-de-tiempo?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### CANCELADOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/cancelados?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}

### ==============================
### CERRADOS
### ==============================
GET {{base_url}}/pedidos/estadisticas/cerrados?from={{from}}&to={{to}}
Authorization: Bearer {{token_socio}}