@base = http://localhost/Programacion3/trabajoPractico-Final
@token_socio = YOUR_TOKEN_HERE
@token_mozo = YOUR_TOKEN_HERE
@token_cocinero = YOUR_TOKEN_HERE
@token_bartender = YOUR_TOKEN_HERE
@token_cervecero = YOUR_TOKEN_HERE

### pruebas sueltas acá
GET {{base}}/mesas

###
GET {{base}}/productos

###
GET {{base}}/pedidos
Authorization: Bearer {{token_socio}}